// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-06-20T09:40:08.028Z
// Chain ID: 11155931 (RISE Testnet)

// Import ABIs
import MockUSDCABI from './abi/MockUSDC.json';
import PriceOracleV2ABI from './abi/PriceOracleV2.json';
import LeverageTradingV3ABI from './abi/LeverageTradingV3.json';

export const contracts = {
  MockUSDC: {
    address: '0x22b1c5c2c9251622f7efb76e356104e5af0e996a' as const,
    deploymentTxHash: '0x07c9edc371ef25f93b75981d2620a8d6771570f2239b6722dfcf156aad3f3403',
    blockNumber: 0xe9d201,
    abi: MockUSDCABI
  },
  PriceOracleV2: {
    address: '0x5a569ad19272afa97103fd4dbadf33b2fcbaa175' as const,
    deploymentTxHash: '0x3466e7348b2bff1ff773bd918c491fba2bb5f2ee164dcd89390d9471309d596d',
    blockNumber: 0xe9d201,
    abi: PriceOracleV2ABI
  },
  LeverageTradingV3: {
    address: '0x696358bbb1a743052e0e87bed78aad9d18f0e1f4' as const,
    deploymentTxHash: '0x691be58d2cc50616deb652e7f3b62a8cd8ecfa6d107e45a6637abc552ef8cb04',
    blockNumber: 0xe9d201,
    abi: LeverageTradingV3ABI
  }
} as const;

// Type exports
export type ContractName = keyof typeof contracts;
export type Contracts = typeof contracts;

// Helper functions
export function getContract<T extends ContractName>(name: T): Contracts[T] {
  return contracts[name];
}

export function getContractAddress(name: ContractName): string {
  return contracts[name].address;
}

export function getContractABI(name: ContractName) {
  return contracts[name].abi;
}

// Re-export specific contracts for convenience
export const MOCKUSDC_ADDRESS = '0x22b1c5c2c9251622f7efb76e356104e5af0e996a' as const;
export const MOCKUSDC_ABI = MockUSDCABI;
export const PRICEORACLEV2_ADDRESS = '0x5a569ad19272afa97103fd4dbadf33b2fcbaa175' as const;
export const PRICEORACLEV2_ABI = PriceOracleV2ABI;
export const LEVERAGETRADINGV3_ADDRESS = '0x696358bbb1a743052e0e87bed78aad9d18f0e1f4' as const;
export const LEVERAGETRADINGV3_ABI = LeverageTradingV3ABI;
