// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-06-20T09:40:08.029Z

import { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL } from '@/config/chain';

// Re-export for backward compatibility
export { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL };

// Contract addresses for WebSocket subscriptions
export const CONTRACTS = {
  "MockUSDC": "0x22b1c5c2c9251622f7efb76e356104e5af0e996a",
  "PriceOracleV2": "0x5a569ad19272afa97103fd4dbadf33b2fcbaa175",
  "LeverageTradingV3": "0x696358bbb1a743052e0e87bed78aad9d18f0e1f4"
} as const;

// Re-export specific contract addresses
export const MOCKUSDC_ADDRESS = '0x22b1c5c2c9251622f7efb76e356104e5af0e996a' as const;
export const PRICEORACLEV2_ADDRESS = '0x5a569ad19272afa97103fd4dbadf33b2fcbaa175' as const;
export const LEVERAGETRADINGV3_ADDRESS = '0x696358bbb1a743052e0e87bed78aad9d18f0e1f4' as const;
